buildpack:
  name: Blazar-Buildpack-Java
  branch: rrotella-patch-2

env:
  SET_VERSION_OVERRIDE: "4.12.0-$GIT_BRANCH-SNAPSHOT"
  MAVEN_OPTS: -Xmx2048m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djansi.force=true

buildResources:
  cpus: 4
  memoryMb: 4096

